### ISSUE TITLE
Client side id not documented

### ISSUE THREAD

**Issue by rolyv** [terraform-providers/terraform-provider-launchdarkly#1]
It appears that the environment resource is properly exporting the `client_side_id` attribute, but it's not documented on the site.

**Comment by ldhenry** [comment]
Hi @rolyv,

Thanks for bringing this to our attention. I'll be sure to update the docs to address this issue.

Thanks,
Henry

**Comment by ldhenry** [comment]
Thanks again @rolyv, the docs have now been updated.
