### ISSUE TITLE
Default values for boolean flags

### ISSUE THREAD

**Issue by eakraly** [terraform-providers/terraform-provider-launchdarkly#10]
I am trying to minimize the amount of code I have to write and maintain per environment.
One way to do that is to have ability to set sane defaults in `launchdarkly_feature_flag`. But today it is not possible - because both default value and targeting value are the same and there is no way to set them.
For boolean flag, sane (to me) defaults means that default rule would be true, and If targeting is off, serve false. In this way when you set targeting to true - true served, if targeting is set to false - false is served.

That is the only way I found I can do that:

Example:
```
resource "launchdarkly_feature_flag" "boolean_flag" {
  project_key    = launchdarkly_project.project.key
  key            = "boolean_flag"
  name           = "boolean_flag"
  variation_type = "boolean"
  variations {
    value  = false 
  } 
  variations {
    value  = true
  } 
}

// This whole block is required
resource "launchdarkly_feature_flag_environment" "boolean_flag_test" {
  flag_id           = launchdarkly_feature_flag.boolean_flag.id
  env_key           = boolean_flag.test.key
  targeting_enabled = false
  flag_fallthrough {
    variation = 1
  }
}
```

The whole definition of variations for boolean is verbose and unnecessary. The only reason it is there is that the default today is reverse order. And as we change order of variations we need to select proper index of variation for `flag_fallthrough`

It would make more sense to allow defaults definition in `launchdarkly_feature_flag` itself and not in `launchdarkly_feature_flag_environment` (not only for boolean). Doing that allows to skip `launchdarkly_feature_flag_environment` definition per environment where it is not different from default.

One way to do that is to use first variation to be the default (targeting off) and last variation to be served when targeting is on. For boolean, both could be assumed in the way consistent with the targeting itself without verbosity of defining variations.

```
resource "launchdarkly_feature_flag" "boolean_flag" {
  project_key    = launchdarkly_project.project.key
  key            = "boolean_flag"
  name           = "boolean_flag"
  variation_type = "boolean" >> Assume default false, Targeting on serves true.
} 
```

Thanks!

**Comment by ldhenry** [comment]
Hi @eakraly,

This sounds like a reasonable change. I'll need to look into this a little deeper, but assuming everything is straightforward I should be able to get this into the next release.

Thanks for the feedback!

**Comment by eakraly** [comment]
Hi!
Any plans to get this change into code?

**Comment by ldhenry** [comment]
He @eakraly,

So I missed this comment earlier. The good news is our application team has recently released a [new feature](https://launchdarkly.com/blog/launched-choose-your-default-feature-flag-variations/) that should help resolve this issue. Since the issue and #18 have a lot in common, I am going to try to get this feature prioritized in the near future.

Thank you for your patience,
Henry

**Comment by ldhenry** [comment]
Hi @eakraly, we added `default_on_variation` and `default_off_variation` to `launchdarkly_feature_flag` in v1.3.0. When setting these up, keep in mind the defaults should be set to the default variation *value* (i.e. `true`, `false` for booleans).

Thanks again for your patience and feedback!

Cheers,
Henry
