### ISSUE TITLE
API/SDK/Client Keys should not be stored

### ISSUE THREAD

**Issue by bschaeffer** [terraform-providers/terraform-provider-launchdarkly#11]
It makes no sense to store these keys in the state file. First, storing sensitive keys here is not a great default, especially since you cannot opt-out of it. Second, you cannot alter these values through the terraform resource and since your only option to update these keys is outside of terraform, it makes no sense to track them inside of terraform.

**Comment by ldhenry** [comment]
Hey @bschaeffer,

I agree with you. Setting the token in the state file is primarily done for illustrative purposes in the docs. I would strongly recommend using the `LAUNCHDARKLY_ACCESS_TOKEN` environment variable instead.

**Comment by bschaeffer** [comment]
Nope, I'm talking about [the code that stores the API/SDK/Client keys for the environment in the statefile](https://github.com/terraform-providers/terraform-provider-launchdarkly/blob/master/launchdarkly/resource_launchdarkly_environment.go#L83).

**Comment by bschaeffer** [comment]
To elaborate, we do not use terraform to store sensitive values, and it doesn't make sense to store the API key in the state file if there is no way to update it via the terraform resource. IMO, these keys should be resources themselves, that way developers can opt-in to tracking API keys in version control if they want to.

**Comment by ldhenry** [comment]
That's good feedback. I'll look into the implications of deprecating the `api_key` attribute from the from the `launchdarkly_environment` resource. 

I think it might make sense to create a new `launchdarkly_environment` *data source* because I imagine plenty of users would want make references to their SDK key in other non-LaunchDarkly Terraform resources.

**Comment by ldhenry** [comment]
Hey @bschaeffer 

Sorry for such a long delay in response.

I did some research and talked it over with the team and for now we are going to keep the API/SDK/Client keys in the statefile, primary based on what is outlined in Hashicorp's best practices on [handling sensitive values in state](https://www.terraform.io/docs/extend/best-practices/sensitive-state.html). I do still plan to create a `launchdarkly_environment` data source. I just need to find the time.

Thanks,
Henry
