### ISSUE TITLE
Issues creating variations with boolean types

### ISSUE THREAD

**Issue by jordan-simonovski** [terraform-providers/terraform-provider-launchdarkly#15]
Hi there, I'm currently running into an issue when creating a new feature flag with boolean variations.
The code snippet for the resource:

```
resource "launchdarkly_feature_flag" "ssm_secrets" {
    project_key = "${launchdarkly_project.platform_tools.key}"
    key         = "ssm-secret-check"
    name        = "ssm-secret-check"
    description = "This flag is for the SSM Secret Checking feature."

    variation_type = "boolean"
    variations {
        value   = false
    }
    variations {
        value   = true
    }
}
```

and the error I'm getting is the following:
```
1 error occurred:
	* launchdarkly_feature_flag.ssm_secrets: 1 error occurred:
	* launchdarkly_feature_flag.ssm_secrets: failed to update flag with name "ssm-secret-check" key "ssm-secret-check" for projectKey "platform-tools": failed to update flag "ssm-secret-check" in project "platform-tools": 400 Bad Request: {"code":"invalid_request","message":"Flag variations must all be distinct"}

```

**Comment by ldhenry** [comment]
Hi @jordan-simonovski ,

I believe our application team recently made some changes to the flag variation code that could be related. I'll consult with them as I continue to investigate this issue. However, I am having a hard time reproducing this error with an isolated `.tf` file in a new working directory:
```
terraform {
  required_providers {
    launchdarkly = "~> 1.0"
  }
}

resource "launchdarkly_feature_flag" "ssm_secrets" {
    project_key = "dummy-project"
    key         = "ssm-secret-check"
    name        = "ssm-secret-check"
    description = "This flag is for the SSM Secret Checking feature."

    variation_type = "boolean"
    variations {
        value   = false
    }
    variations {
        value   = true
    }
}
```
Is the error behavior consistent for you or intermittent?

**Comment by jordan-simonovski** [comment]
Hey @ldhenry, 

I was trying out a few variations of this last night, and it was fairly consistent. 

Worth noting is that I'm running Terraform v 0.12.20.

**Comment by ldhenry** [comment]
Hi @jordan-simonovski ,

Sorry for the delayed response. I think our application team may have fixed this issue. Please let me know if you are still experiencing this problem.

Thanks,
Henry

**Comment by ldhenry** [comment]
Closing for now. Please re-open this issue if you are still experienced trouble.

Thanks,
Henry

**Comment by sadavartia** [comment]
Hi @ldhenry , 
I am experiencing the same issue as reported above here.
Also, Is there a terraform version dependency for the LaunchDarkly terraform provider ?
I am using terraform `v0.11.11`
Launchdarkly plugin version `v1.2.2`
