### ISSUE TITLE
Can't set tags on Environment resource

### ISSUE THREAD

**Issue by snasirca** [terraform-providers/terraform-provider-launchdarkly#5]
The `launchdarkly_environment` resource does not support `tags` which I would like to be able to set through terraform.

**Comment by ldhenry** [comment]
Hi @snasirca, thanks for bringing this to my attention. I will work to get this into the next release.

**Comment by ldhenry** [comment]
Hi @snasirca, this feature has been added into the freshly minted 1.0.0 release. Thanks again for the feedback.

**Comment by snasirca** [comment]
Thank you for the quick turnaround! Will try it out in our infra.

**Comment by snasirca** [comment]
Tried it out in production and it works perfectly.
