### ISSUE TITLE
Can't unset maintainer_id

### ISSUE THREAD

**Issue by jamielennox** [terraform-providers/terraform-provider-launchdarkly#6]
So i'm more familiar with terraform than I am launchdarkly so this might not be possible. 

I'm trying to import an existing launchdarkly environment into terraform control using the standard `terraform import`, and there is some oddity around the way `maintainer_id` is done. 

If I specify a `maintainer_id` it's respected, and i can change the flag from one maintainer to another. 

If i have a feature flag with a maintainer then I would expect that if i set `maintainer_id = ""` or removed `maintainer_id` altogether then it should remove it from the flag. However the way it's defined as [both `computed` and `optional`](https://github.com/terraform-providers/terraform-provider-launchdarkly/blob/76af0de33f053692e82867c1492504e9dd3f671e/launchdarkly/resource_launchdarkly_feature_flag.go#L46-L47) means that i can't unset this. 

It may be something I don't understand on the launchdarkly side, but i would think this value should not be `computed`.

**Comment by jamielennox** [comment]
So to clarify - i get that if you don't set a maintainer_id it's supposed to default to the current user. Maybe that should be something that is resolved and set on the client side before sending to the server and remove computed?

**Comment by ldhenry** [comment]
Hi @jamielennox, thanks for the feedback. I agree that the value should not be computed. I'll start working on this today.

**Comment by ldhenry** [comment]
Hi @jamielennox, my PR to address this issue made it into the newly minted 1.0.0 release. Thanks again for your feedback.

**Comment by jamielennox** [comment]
Great, thank you.
